[runner]
magicEnabled = false

[client]
showToolbarNavigation = false

[theme]
default = "light"
primaryColor = "#FF8C00"
backgroundColor = "#F9FAFB"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#111827"
