[runner]
magicEnabled = false

[client]
showToolbarNavigation = false

[theme]
default = "light"
primaryColor = "#ff6b36"
backgroundColor = "#F9FAFB"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#111827"
